# Generated by Django 5.0.6 on 2024-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authrequest',
            name='key',
        ),
        migrations.RemoveField(
            model_name='authrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='authrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
