# Generated by Django 5.0.6 on 2024-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth_app', '0002_remove_authrequest_key_remove_authrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrequest',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
